enabled: true
usePassword: false
cluster:
  enabled: false
  slaveCount: 0
auth:
  enabled: false
master:
  disableCommands: []
  resources:
    requests:
      cpu: 50m
      memory: 200Mi
  nodeSelector:
    project: {{ env.CI_PROJECT_NAME }}-{{ env.CI_COMMIT_REF_SLUG }}
  tolerations:
    - key: "project"
      operator: "Equal"
      value: '{{ env.CI_PROJECT_NAME }}-{{ env.CI_COMMIT_REF_SLUG }}'
      effect: "NoSchedule"
replica:
  enabled: false
  replicaCount: 0