com.mindsmiths.armory.events.UserConnectedEvent:
  - !GetOrCreateAgentByConnection
    connectionName: armory
    connectionField: connectionId
    agentType: agents.Ava
com.mindsmiths.armory.events.SubmitEvent:
  - !GetOrCreateAgentByConnection
    connectionName: armory
    connectionField: connectionId
    agentType: agents.Ava
com.mindsmiths.armory.events.UserDisconnectedEvent:
  - !GetOrCreateAgentByConnection
    connectionName: armory
    connectionField: connectionId
    agentType: agents.Ava
com.mindsmiths.employeeManager.employees.Employee:
  - !GetOrCreateAgentByConnection
    connectionName: employeeId
    connectionField: id
    agentType: agents.Ava
